### ISSUE TITLE
Folder 'assets' problem with GitHub pages

### ISSUE THREAD

**Issue by faresdjefaflia** [gheyth/al-furqan#8]

**Comment by frs99** [comment]
[[612fc97](https://github.com/gheyth/al-furqan/commit/612fc97437a212e9d186e1ae39c87a665f47bc4a)](https://github.com/gheyth/al-furqan/commit/612fc97437a212e9d186e1ae39c87a665f47bc4a)  **not working**

**Comment by faresdjefaflia** [comment]
612fc97 not working

**Comment by faresdjefaflia** [comment]
e471a09 It's the solution
